#ifndef TEMP_SENSOR_PRIVATE_H_
#define TEMP_SENSOR_PRIVATE_H_

/* LM35 GIVES 10mV PER DEGREE CELSIUS , Vref = 5000mV , ADC RESOLUTION = 1023 ( 10-bit ) */
#define TEMP_SENSOR_VREF_mV    5000
#define TEMP_SENSOR_ADC_MAX    1023


#endif /* TEMP_SENSOR_PRIVATE_H_ */
