#ifndef MOTOR_CONFIG_H_
#define MOTOR_CONFIG_H_

/* MOTOR1 PIN CONFIGURATION ( PORTB IS FREE : PORTA -> KPD , PORTC -> LCD CONTROL , PORTD -> LCD DATA ) */
#define MOTOR1_PORT     DIO_PORTB
#define MOTOR1_PIN1     DIO_PIN3
#define MOTOR1_PIN2     DIO_PIN4


#endif /* MOTOR_CONFIG_H_ */
